# Pubchem molecules with optical rotation values
[source]
title = "Scraping optical rotation values from molecules in PubChem"
authors = "Liyah A Coleman, Richard C Gerkin"

[raw]
"raw_data.csv" = "Values were extracted from PubChem"

[processed]
"molecules.csv" = "Molecules used"
"physics.csv" = "Dataframe of the scraped opr values"

[code]
"main.py" = "Processing workflow"
