# Manifest for Mainland et al, 2015 data
[source]
doi = "https://doi.org/10.1038/sdata.2015.2"
title = "Human olfactory receptor responses to odorants"
authors = "Joel D Mainland, Yun R Li, Ting Zhou, Wen Ling L Liu, Hiroaki Matsunami"

[raw]
No Raw Data available

[processed]
main.ipynb = "Processing workflow"
molecules.csv = "Molecules used"
behavior.csv = "Compiled odor thresholds and threshold algorithm parameters"
