# Manifest for Bushdid et al, 2014 data
[source]
doi = "https://doi.org/10.1038/sdata.2015.2"
title = "Human Olfactory Receptor Responses to Odorants"
authors = "C Bushdid, MO Magnasco, LB Vosshall, A Keller"

[raw]
No raw data

[processed]
main.ipynb = "Processing workflow"
molecules.csv = "Molecules used"
behavior.csv = "Log EC50s for all OR/odor pairs that pass the three statistical criteria outlined in the methods"
