# Pubchem molecules with optical rotation values
[source]
title = "Scrapping optical rotation values from molecules in PubChem"
authors = "Richard C Gerkin, Liyah A Coleman"

[raw]
"raw_data" = Values were extracted from PubChem

[processed]
"main.py" = "code for scrapping"
"main.ipynb" = "notebook for running code"
"molecules.csv" = "Molecules used"
"attributes.csv" = "dataframe of the scrpped opr values"