# Manifest for Abraham et al, 2012 data
[source]
doi = "https://dx.doi.org/10.1523%2FJNEUROSCI.3736-13.2014"
title = "Tuning to Odor Solubility and Sorption Pattern in Olfactory Epithelial Responses"
authors = "John W. Scott, Lisa Sherrill, Jianbo Jiang and Kai Zhao"

[raw]
No raw data

[processed]
main.ipynb = "Processing workflow"
molecules.csv = "Molecules used"
behavior.csv = "Compiled odor thresholds and threshold algorithm parameters"
